site_name: Calva User Guide
docs_dir: docs/site
theme:
  name: material
  custom_dir: docs/site/theming
  favicon: img/favicon.ico
  logo: img/calva-symbol-white.svg
extra_css:
  - stylesheets/extra.css
site_url: https://calva.io
site_description: Learn how to use Calva to boost your Clojure and ClojureScript coding in VS Code.
google_analytics:
  - UA-69796730-5
  - auto
repo_name: Calva
repo_url: https://github.com/BetterThanTomorrow/calva
edit_uri: edit/published/docs/site
strict: true
markdown_extensions:
  - admonition
  - codehilite
nav:
  - index.md
  - Start Here:
    - getting-started.md
    - connect.md
    - try-first.md
    - finding-commands.md
    - eval-tips.md
    - clojure-lsp.md
  - Features:
    - commands-top10.md
    - output.md
    - formatting.md
    - paredit.md
    - debugger.md
    - pprint.md
    - refactoring.md
    - test-runner.md
    - connect-sequences.md
    - custom-commands.md
    - linting.md
    - ns-form-deriving.md
  - customizing.md
  - Using Calva with X:
    - rebl.md
    - reveal.md
    - vim.md
    - wsl.md
    - remote-development.md
    - live-share.md
    - luminus.md
    - re-frame-template.md
    - polylith.md
    - krell.md
    - static-only.md
    - parinfer.md
  - Etcetera:
    - workspace-layouts.md
    - quirks.md
  - In Depth:
    - jack-in-guide.md
  - sponsors.md
  - merch.md
