site_name: Calva User Guide
docs_dir: docs/site
theme:
  name: material
  custom_dir: docs/site/theming
  favicon: img/favicon.ico
  logo: img/calva-symbol-white.svg
  features:
    - search.share
  #  - toc.integrate
extra_css:
  - stylesheets/extra.css
site_url: https://calva.io
site_description: Learn how to use Calva to boost your Clojure and ClojureScript coding in VS Code.
extra:
  analytics:
    provider: google
    property: UA-69796730-5
repo_name: Calva
repo_url: https://github.com/BetterThanTomorrow/calva
edit_uri: edit/published/docs/site
strict: true
plugins:
  - search:
      separator: '[\s\-\._]'
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
      cards_color:
        fill: "#db9550"
        text: "#fafafa"
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
nav:
  - index.md
  - Start Here:
    - getting-started.md
    - connect.md
    - try-first.md
    - finding-commands.md
    - eval-tips.md
  - why-calva.md
  - Features:
    - commands-top10.md
    - evaluation.md
    - rich-comments.md
    - clojuredocs.md
    - Structural Editing:
      - paredit.md
      - parinfer.md
      - formatting.md
      - highlight.md
    - debugger.md
    - output.md
    - pprint.md
    - refactoring.md
    - test-runner.md
    - connect-sequences.md
    - custom-commands.md
    - linting.md
    - namespace-form-auto-creation.md
  - clojure-lsp.md
  - nrepl_and_cider-nrepl.md
  - customizing.md
  - Using Calva with X:
    - wsl.md
    - remote-development.md
    - live-share.md
    - vim.md
    - reveal.md
    - babashka.md
    - nbb.md
    - luminus.md
    - re-frame-template.md
    - polylith.md
    - krell.md
    - rebl.md
    - static-only.md
  - Etcetera:
    - emacs-keybindings.md
    - workspace-layouts.md
    - quirks.md
  - In Depth:
    - jack-in-guide.md
  - Guides:
    - get-started-with-clojure.md
  - tao.md
  - contribute.md
  - sponsors.md
  - merch.md
